apiVersion: v1
kind: Namespace
metadata:
  name: openclaw
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openclaw-helm
  namespace: flux-system
spec:
  interval: 24h
  url: https://serhanekicii.github.io/openclaw-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclaw
  namespace: openclaw
spec:
  interval: 1h
  chart:
    spec:
      chart: openclaw
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: openclaw-helm
        namespace: flux-system
      interval: 24h
  values:
    app-template:
      controllers:
        main:
          containers:
            main:
              envFrom:
                - secretRef:
                    name: openclaw-env-secret
      ingress:
        main:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: openclaw.kaique.cloud
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
                    port: http
          tls:
            - secretName: openclaw-tls
              hosts:
                - openclaw.kaique.cloud
      persistence:
        data:
          enabled: true
          storageClass: local-path
