apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.containeroo.ch
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 1h
  chart:
    spec:
      chart: local-path-provisioner
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 24h
  values:
    storageClass:
      create: true
      name: local-path
      defaultClass: true
      reclaimPolicy: Retain
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /opt/local-path-provisioner
