#!/bin/bash
# Exposes a TCP or UDP port on the VPS edge, proxying it to all registered K8s nodes.
# Uses nginx stream module for TCP/UDP proxy (not HTTP — works for Minecraft, game servers, etc).
#
# Usage:
#   ./add-port.sh <port> <tcp|udp>
#
# Examples:
#   ./add-port.sh 25565 tcp   # Minecraft Java
#   ./add-port.sh 19132 udp   # Minecraft Bedrock
#   ./add-port.sh 27015 udp   # Steam game server

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH_KEY="$SCRIPT_DIR/../ansible/.ssh/id_ed25519"

PORT="${1:-}"
PROTO="${2:-}"

# ============================================================
# Validation
# ============================================================
if [ -z "$PORT" ] || [ -z "$PROTO" ]; then
  echo "Usage: $0 <port> <tcp|udp>"
  echo "  Example: $0 25565 tcp"
  exit 1
fi

if [ "$PROTO" != "tcp" ] && [ "$PROTO" != "udp" ]; then
  echo "ERROR: Protocol must be 'tcp' or 'udp'"
  exit 1
fi

if ! [[ "$PORT" =~ ^[0-9]+$ ]] || [ "$PORT" -lt 1 ] || [ "$PORT" -gt 65535 ]; then
  echo "ERROR: Port must be a number between 1 and 65535"
  exit 1
fi

if [ ! -f "$SCRIPT_DIR/.vps-ip" ]; then
  echo "ERROR: VPS not set up yet. Run ./setup-vps.sh first."
  exit 1
fi

VPS_IP=$(cat "$SCRIPT_DIR/.vps-ip")
VPS_USER=$(cat "$SCRIPT_DIR/.vps-user" 2>/dev/null || echo "ubuntu")

SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 -o BatchMode=yes"
vssh() { ssh $SSH_OPTS "${VPS_USER}@${VPS_IP}" "$@"; }

echo "=== Adding port $PORT/$PROTO to VPS edge ==="
echo ""

# ============================================================
# Step 1: Ensure stream.conf.d/ports/ exists
# ============================================================
vssh "sudo mkdir -p /etc/nginx/stream.conf.d/ports"

# Ensure nginx.conf includes stream block
vssh "
  if ! grep -q 'stream.conf.d' /etc/nginx/nginx.conf; then
    printf '\nstream {\n    include /etc/nginx/stream.conf.d/*.conf;\n    include /etc/nginx/stream.conf.d/ports/*.conf;\n}\n' | sudo tee -a /etc/nginx/nginx.conf > /dev/null
    echo '  Added stream block to nginx.conf'
  fi
"

# ============================================================
# Step 2: Create port config file (will be regenerated with real IPs)
# ============================================================
echo "[1/3] Creating stream port config on VPS..."

PORT_CONF="/etc/nginx/stream.conf.d/ports/${PORT}-${PROTO}.conf"
UPSTREAM_NAME="k8s_stream_${PORT}"

# Write an initial placeholder — regen-nginx-upstream.sh will fill in real IPs
vssh "sudo tee ${PORT_CONF} > /dev/null << PORTEOF
upstream ${UPSTREAM_NAME} {
    server 127.0.0.1:65535 down;  # placeholder — regenerated by regen-nginx-upstream.sh
}
server {
    listen ${PORT}$([ "$PROTO" = "udp" ] && echo " udp" || echo "");
    proxy_pass ${UPSTREAM_NAME};
}
PORTEOF
"
echo "  ✓ Port config created: $PORT_CONF"
echo ""

# ============================================================
# Step 3: Regenerate all upstreams (fills in real node IPs)
# ============================================================
echo "[2/3] Populating upstream with registered nodes..."
vssh "sudo /usr/local/sbin/regen-nginx-upstream.sh"
echo ""

# ============================================================
# Step 4: Open firewall
# ============================================================
echo "[3/3] Opening firewall on VPS..."
vssh "
  if sudo ufw status | grep -q 'Status: active'; then
    sudo ufw allow ${PORT}/${PROTO}
    echo '  ✓ UFW rule added: ${PORT}/${PROTO}'
  else
    echo '  UFW not active, skipping'
  fi
"
echo ""

echo "=== Port $PORT/$PROTO exposed ==="
echo ""
echo "  Traffic flow:"
echo "    Internet → VPS:$PORT ($PROTO)"
echo "    → nginx stream → all registered nodes:$PORT"
echo "    → K8s NodePort / service"
echo ""
echo "  Make sure your K8s service uses NodePort $PORT or"
echo "  configure your ingress controller to handle this port."
echo ""
